/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoucherGeneratorRouteImport } from './routes/voucher-generator'
import { Route as UserGuideRouteImport } from './routes/user-guide'
import { Route as SeatAssignmentRouteImport } from './routes/seat-assignment'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as IndexRouteImport } from './routes/index'

const VoucherGeneratorRoute = VoucherGeneratorRouteImport.update({
  id: '/voucher-generator',
  path: '/voucher-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const UserGuideRoute = UserGuideRouteImport.update({
  id: '/user-guide',
  path: '/user-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatAssignmentRoute = SeatAssignmentRouteImport.update({
  id: '/seat-assignment',
  path: '/seat-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flights': typeof FlightsRoute
  '/seat-assignment': typeof SeatAssignmentRoute
  '/user-guide': typeof UserGuideRoute
  '/voucher-generator': typeof VoucherGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flights': typeof FlightsRoute
  '/seat-assignment': typeof SeatAssignmentRoute
  '/user-guide': typeof UserGuideRoute
  '/voucher-generator': typeof VoucherGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flights': typeof FlightsRoute
  '/seat-assignment': typeof SeatAssignmentRoute
  '/user-guide': typeof UserGuideRoute
  '/voucher-generator': typeof VoucherGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flights'
    | '/seat-assignment'
    | '/user-guide'
    | '/voucher-generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flights'
    | '/seat-assignment'
    | '/user-guide'
    | '/voucher-generator'
  id:
    | '__root__'
    | '/'
    | '/flights'
    | '/seat-assignment'
    | '/user-guide'
    | '/voucher-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlightsRoute: typeof FlightsRoute
  SeatAssignmentRoute: typeof SeatAssignmentRoute
  UserGuideRoute: typeof UserGuideRoute
  VoucherGeneratorRoute: typeof VoucherGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voucher-generator': {
      id: '/voucher-generator'
      path: '/voucher-generator'
      fullPath: '/voucher-generator'
      preLoaderRoute: typeof VoucherGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-guide': {
      id: '/user-guide'
      path: '/user-guide'
      fullPath: '/user-guide'
      preLoaderRoute: typeof UserGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seat-assignment': {
      id: '/seat-assignment'
      path: '/seat-assignment'
      fullPath: '/seat-assignment'
      preLoaderRoute: typeof SeatAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlightsRoute: FlightsRoute,
  SeatAssignmentRoute: SeatAssignmentRoute,
  UserGuideRoute: UserGuideRoute,
  VoucherGeneratorRoute: VoucherGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
