// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Get DATABASE_URL with fallback - check if env var exists first
const databaseUrl = process.env.DATABASE_URL || "file:./data/dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `bun run prisma/seed.ts`,
  },
  datasource: {
    url: databaseUrl,
  },
});
